/**
* @fileoverview This file is generated by the Angular template compiler.
* Do not edit.
* @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
* tslint:disable
*/ 
var styles = [".ui-badge {\n  position: relative;\n  vertical-align: middle;\n  display: inline-block;\n}\n\n.ui-badge-content {\n  background-color: #f56c6c;\n  border-radius: 10px;\n  color: #fff;\n  display: inline-block;\n  font-size: 12px;\n  height: 18px;\n  line-height: 18px;\n  padding: 0 6px;\n  text-align: center;\n  white-space: nowrap;\n  border: 1px solid #fff;\n}\n\n.ui-item {\n  margin-right: 40px;\n}\n\n.ui-badge-content.fixed {\n  position: absolute;\n  top: 0;\n  right: 10px;\n  transform: translateY(-50%) translateX(100%);\n}\n\n.ui-badge-content.dot {\n  height: 8px;\n  width: 8px;\n  padding: 0;\n  right: 0;\n  border-radius: 50%;\n}\n\n.ui-badge-content.fixed.dot {\n  right: 5px;\n}\n\n.ui-position {\n  margin-top: 10px;\n  margin-right: 40px;\n}\n\n"];
export { styles as styles };
//# sourceMappingURL=badge.css.ngstyle.js.map